### ISSUE TITLE
UDOO Bluetooth periodically switches off

### ISSUE THREAD

**Issue by afolarin** [RADAR-CNS/radar-prmt-android#53]
This has been observed a few times by both @sboettcher and us. Looks like UDOO Bluetooth connection switches off without any clear cause (for e.g. it has worked for periods of upto 15 days without issue).

A potential workaround may be to have a service monitor Bluetooth and restar it, as the UDOOs are rooted this should be possible @yatharthranjan.

![img-20171106-wa0001](https://user-images.githubusercontent.com/2489685/32439656-8dffe5c6-c2e7-11e7-8cef-efcac951bd52.jpg)

**Comment by yatharthranjan** [comment]
Yes turning on bluetooth automatically should be fairly easy to implement but its not good practice to do it without asking the user. So if there is no solution then this can be done. What do you say @sboettcher and @afolarin ?

**Comment by blootsvoets** [comment]
Indeed, it can be implemented inside UDOO in a separate app, but the current app will always request the permission. The app can avoid requesting the permission if such a service is running. That would need to be a configurable setting that also affects radar-commons-android

**Comment by afolarin** [comment]
@blootsvoets @yatharthranjan agree. We would only want this behaviour in the UDOO version, not the general pRMT. If there is any user requirements, we should have device disconnection monitor functionality fixed RADAR-CNS/RADAR-Backend#37 (hopefully this will reduce the data loss window for a range of these disconnection issues).

**Comment by sboettcher** [comment]
I agree it is a UDOO only problem. However I think the actual problem (for now) is that the E4 is disconnected, which has to be solved via hands-on anyway. And so far I think this issue does not occur often enough to warrant large-scale revisions to the code. But if it is possible to do this quickly it might be worthwhile to implement this in a separate branch.

**Comment by afolarin** [comment]
ok agree. Let's test the alerting/notifier, I think this adequately solves a range of these sporadic problems
